name = "w3name-staging"
main = "dist/index.mjs"
compatibility_date = "2022-06-10"

[build]
command = "npm run build"

[durable_objects]
bindings = [
    { name = "NAME_ROOM", class_name = "NameRoom0" },
    { name = "IPNS_RECORD", class_name = "IPNSRecord" }
]

[env.test.vars]
REBROADCAST_INTERVAL_MS = 500
PUBLISHER_ENDPOINT_URL = "http://127.0.0.1:8000"
PUBLISHER_AUTH_SECRET = 123456

[[migrations]]
tag = "v1"
new_classes = ["NameRoom0", "IPNSRecord"]
