name: Api
on:
  push:
    branches:
      - main
    paths:
      - 'packages/api/**'
      - '.github/workflows/api.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/api/**'
      - '.github/workflows/api.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: packages/api
      - run: npm run build --workspace packages/api
      - run: npm test --workspace packages/api

