name: Client
on:
  push:
    branches:
      - main
    paths:
      - 'packages/client/**'
      - '.github/workflows/client.yml'
  pull_request:
    types:
      - opened
      # Triggered when a pull request's head branch is updated.
      # For example, when the head branch is updated from the base branch, when new commits are pushed to the head branch, or when the base branch is changed.
      - synchronize
    paths:
      - 'packages/client/**'
      - '.github/workflows/client.yml'
jobs:

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - run: npm run lint --workspace packages/client
      - run: npm run build --workspace packages/client
      - run: npm test --workspace packages/client

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: tag-release
        with:
          path: packages/client
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          monorepo-tags: true
          package-name: w3name
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Other Changes","hidden":false}]'
      - uses: actions/checkout@v2
        if: ${{ steps.tag-release.outputs.releases_created }}
      - uses: actions/setup-node@v2
        if: ${{ steps.tag-release.outputs.releases_created }}
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      - uses: bahmutov/npm-install@v1
        if: ${{ steps.tag-release.outputs.releases_created }}
      # --- Client deploy steps  ---------------------------------------------
      - name: Client - NPM Publish
        if: ${{ steps.tag-release.outputs.releases_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        run: npm publish --workspace packages/client

  typedoc:
    name: API docs
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - run: npm run typedoc --workspace packages/client
      - uses: web3-storage/add-to-web3@v2
        id: web3
        with:
          web3_token: ${{ secrets.WEB3_STORAGE_KEY }}
          path_to_add: 'packages/client/generated-docs'
      - run: echo added typedoc output to web3.storage. cid -- ${{ steps.web3.outputs.cid }}
      - run: echo typedoc URL -- https://${{ steps.web3.outputs.cid }}.ipfs.nftstorage.link
      - uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: 'API docs'
          description: 'Preview of generated client API docs'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
          target_url: "https://${{ steps.web3.outputs.cid }}.ipfs.nftstorage.link"
      - run: gh-pages -d generated-docs
        if: ${{ steps.tag-release.outputs.releases_created }}
